services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    env_file:
      - .env
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
  redis:
    image: 'redis:alpine'
    env_file:
      - .env
    ports:
      - '6379:6379'
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
