services:
  mongodb:
    image: 'mongo:latest'
    env_file:
      - .env
    ports:
      - '27017:27017'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    env_file:
      - .env
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
  redis:
    image: 'bitnami/redis:latest'
    env_file:
      - .env
    ports:
      - '6379:6379'
