spring:
  application:
    name: backend

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}

  ai:
    clova:
      base-url: https://clovastudio.stream.ntruss.com/
      api-key: ${CLOVA_API_KEY}
      chat:
        app-name: testapp
      speech:
        invoke-url: ${CLOVA_SPEECH_INVOKE_URL}
        secret-key: ${CLOVA_SPEECH_SECRET_KEY}

  cloud:
    ncp:
      storage:
        access-key: ${NCP_ACCESS_KEY}
        secret-key: ${NCP_SECRET_KEY}
        region: kr-standard
        endpoint: https://kr.object.ncloudstorage.com

  mail:
    host: ${SMTP_HOST}
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  threads:
    virtual:
      enabled: true

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
    connection-timeout: 300000

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true