spring:
  application:
    name: backend

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  jwt:
    secret: ${JWT_SECRET}

  ai:
    clova:
      api-key: ${CLOVA_API_KEY}
      chat:
        app-name: testapp

  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true